# Generated by Django 3.2.7 on 2021-11-27 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex_code', models.CharField(max_length=6)),
                ('rgb_red', models.CharField(max_length=3)),
                ('rgb_green', models.CharField(max_length=3)),
                ('rgb_blue', models.CharField(max_length=3)),
                ('dmc_code', models.CharField(max_length=6)),
                ('dmc_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImageTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
